CREATE PROC [spInsertDataKuesionerMahasiswa]
	@NIM VARCHAR(10),
	@PERTANYAAN_1 DECIMAL(3, 2),
	@PERTANYAAN_2 DECIMAL(3, 2),
	@PERTANYAAN_3 DECIMAL(3, 2),
	@PERTANYAAN_4 DECIMAL(3, 2),
	@PERTANYAAN_5 DECIMAL(3, 2),
	@HASIL INT

AS
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM DATA_KUESIONER
		WHERE NIM = @NIM
	)
	BEGIN
		INSERT INTO DATA_KUESIONER
		VALUES (
			@NIM,
			@PERTANYAAN_1,
			@PERTANYAAN_2,
			@PERTANYAAN_3,
			@PERTANYAAN_4,
			@PERTANYAAN_5,
			@HASIL
		)
	END
	ELSE
	BEGIN
	print('Data sudah ada')
	END
END